<a href="https://colab.research.google.com/github/ShotaSasaki-HU/ASTRO-CAMP-2025/blob/main/tabula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ライブラリ

In [86]:
import pandas as pd
!pip install tabula-py
import tabula
import numpy as np

Requirement already satisfied: tabula-py in /usr/local/lib/python3.12/dist-packages (2.10.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)

# 2020_セジロウンカ日別誘殺数

## tabulaによる表の抽出

In [93]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2020.pdf",
    pages = '79',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r2,0\r0\r0\r0\r0,127\r215\r151\r60\r33,102\r91\r99\r39\r12,25\r40\r645\r179\r33,16\r25\r656\r92\r10,18\r4\r13\r26\r2,13\r5\r4\r23\r1,1\r0\r0\r0\r0,0\r0\r0\r0\r0
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r0\r0,0\r0\r1\r0\r1,57\r41\r35\r8\r1,13\r16\r36\r6\r0,9\r21\r101\r101\r19,8\r12\r81\r46\r16,0\r0\r0\r1\r44,0\r2\r0\r0\r30,0\r1\r0\r0\r0,0\r0\r0\r0\r0
3,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,4\r0\r4\r0\r2,0\r0\r0\r0\r0,1\r0\r1\r0\r4,0\r0\r1\r0\r3,6\r14\r10\r7\r14,1\r11\r8\r3\r10,37\r7\r0\r2\r0,33\r11\r1\r0\r2,21\r0\r4\r0\r0,13\r2\r2\r2\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,3\r0\r6\r2\r2,0\r0\r3\r0\r0,11\r26\r14\r12\r11,12\r13\r5\r4\r8,36\r36\r6\r23\r5,37\r26\r9\r19\r14,1\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r26\r20\r2\r19,2\r19\r10\r0\r6,23\r58\r184\r124\r209,24\r61\r254\r106\r163,1\r8\r10\r16\r10,1\r5\r2\r8\r7,0\r0\r2\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,4\r9\r2\r1\r8\r6,0\r3\r2\r1\r1\r3,25\r7\r74\r95\r170\r28,31\r3\r51\r61\r199\r31,16\r4\r0\r9\r58,15\r3\r1\r7\r40,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [94]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,127,102,25,16,18,13,1,0
1,2,0,0,0,0,0,0,0,0,215,91,40,25,4,5,0,0
2,3,0,0,0,0,0,0,0,0,151,99,645,656,13,4,0,0
3,4,0,0,0,0,0,0,0,0,60,39,179,92,26,23,0,0
4,5,0,0,0,0,0,0,2,0,33,12,33,10,2,1,0,0
5,6,0,0,0,0,0,0,0,0,57,13,9,8,0,0,0,0
6,7,0,0,0,0,0,0,0,0,41,16,21,12,0,2,1,0
7,8,0,0,0,0,0,0,2,1,35,36,101,81,0,0,0,0
8,9,0,0,0,0,0,0,0,0,8,6,101,46,1,0,0,0
9,10,0,0,0,0,0,0,0,1,1,0,19,16,44,30,0,0
10,11,0,0,0,0,4,0,1,0,6,1,37,33,21,13,0,0
11,12,0,0,0,0,0,0,0,0,14,11,7,11,0,2,0,0
12,13,0,0,0,0,4,0,1,1,10,8,0,1,4,2,0,0
13,14,0,0,0,0,0,0,0,0,7,3,2,0,0,2,0,0
14,15,0,0,0,0,2,0,4,3,14,10,0,2,0,0,0,0
15,16,0,0,0,0,1,0,3,0,11,12,36,37,1,1,0,0
16,17,0,0,0,0,0,0,0,0,26,13,36,26,0,0,0,0
17,18,0,0,0,0,0,0,6,3,14,5,6,9,0,0,0,0
18,19,0,0,0,0,0,0,2,0,12,4,23,19,0,0,0,0
19,20,0,0,0,0,0,0,2,0,11,8,5,14,0,0,0,0
20,21,0,0,0,0,0,0,0,2,23,24,1,1,0,0,0,0
21,22,0,0,0,0,0,0,26,19,58,61,8,5,0,0,0,0
22,23,0,0,0,0,0,0,20,10,184,254,10,2,2,0,0,0
23,24,0,0,0,0,0,0,2,0,124,106,16,8,0,0,0,0
24,25,0,0,0,0,0,0,19,6,209,163,10,7,0,0,0,0
25,26,0,0,0,0,0,0,4,0,25,31,16,15,0,0,0,0
26,27,0,0,0,0,0,0,9,3,7,3,4,3,0,0,0,0
27,28,0,0,0,0,0,0,2,2,74,51,0,1,0,0,0,0
28,29,0,0,0,0,0,0,1,1,95,61,9,7,0,0,0,0
29,30,0,0,0,0,0,0,8,1,170,199,58,40,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,6,3,28,31,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [102]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        0.0
5月_オス        0.0
6月_メス       11.0
6月_オス        0.0
7月_メス      120.0
7月_オス       56.0
8月_メス     1850.0
8月_オス     1473.0
9月_メス     1457.0
9月_オス     1203.0
10月_メス     136.0
10月_オス      98.0
11月_メス       2.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [104]:
df.to_csv("セジロウンカ日別誘殺数_2020.csv")

# 2020_トビイロウンカ日別誘殺数

## tabulaによる表の抽出

In [115]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2020.pdf",
    pages = '80',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,"43\r8\r1,040\r204\r46","26\r3\r1,070\r128\r37",18\r11\r48\r133\r1,13\r10\r34\r117\r3,14\r0\r0\r0\r0,10\r2\r0\r1\r3
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r7\r7\r2\r1,0\r6\r8\r2\r0,7\r62\r152\r61\r11,7\r50\r190\r21\r5,2\r0\r4\r14\r337,0\r2\r2\r11\r316,0\r5\r0\r0\r0,0\r0\r0\r0\r0
3,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,2\r0\r1\r3\r1,1\r0\r4\r1\r1,5\r3\r26\r3\r7,4\r0\r13\r2\r6,210\r27\r20\r4\r0,164\r40\r30\r10\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r2\r0\r0\r0,0\r1\r0\r0\r1,61\r57\r46\r185\r30,39\r62\r49\r168\r26,0\r0\r0\r0\r0,1\r0\r1\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r1\r11\r14\r6,0\r0\r11\r9\r9,1\r24\r14\r44\r29,2\r25\r5\r24\r18,30\r0\r3\r0\r2,23\r0\r2\r5\r2,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,3\r1\r46\r175\r67\r46,1\r2\r53\r159\r67\r47,21\r5\r0\r25\r191,27\r4\r1\r18\r127,0\r0\r0\r66\r0\r0,0\r0\r1\r47\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [117]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,0,0,43,26,18,13,14,10
1,2,0,0,0,0,0,0,0,0,0,0,8,3,11,10,0,2
2,3,0,0,0,0,0,0,0,0,0,0,1040,1070,48,34,0,0
3,4,0,0,0,0,0,0,0,0,0,0,204,128,133,117,0,1
4,5,0,0,0,0,0,0,0,0,0,0,46,37,1,3,0,3
5,6,0,0,0,0,0,0,0,0,0,0,7,7,2,0,0,0
6,7,0,0,0,0,0,0,0,0,7,6,62,50,0,2,5,0
7,8,0,0,0,0,0,0,0,0,7,8,152,190,4,2,0,0
8,9,0,0,0,0,0,0,0,0,2,2,61,21,14,11,0,0
9,10,0,0,0,0,0,0,0,0,1,0,11,5,337,316,0,0
10,11,0,0,0,0,0,0,0,0,2,1,5,4,210,164,0,0
11,12,0,0,0,0,0,0,0,0,0,0,3,0,27,40,0,0
12,13,0,0,0,0,0,0,0,0,1,4,26,13,20,30,0,0
13,14,0,0,0,0,0,0,0,0,3,1,3,2,4,10,0,0
14,15,0,0,0,0,0,0,0,0,1,1,7,6,0,0,0,0
15,16,0,0,0,0,0,0,0,0,0,0,61,39,0,1,0,0
16,17,0,0,0,0,0,0,0,0,2,1,57,62,0,0,0,0
17,18,0,0,0,0,0,0,0,0,0,0,46,49,0,1,0,0
18,19,0,0,0,0,0,0,0,0,0,0,185,168,0,1,0,0
19,20,0,0,0,0,0,0,0,0,0,1,30,26,0,0,0,0
20,21,0,0,0,0,0,0,0,0,1,0,1,2,30,23,0,0
21,22,0,0,0,0,0,0,0,0,1,0,24,25,0,0,0,0
22,23,0,0,0,0,0,0,0,0,11,11,14,5,3,2,0,0
23,24,0,0,0,0,0,0,0,0,14,9,44,24,0,5,0,0
24,25,0,0,0,0,0,0,0,0,6,9,29,18,2,2,0,0
25,26,0,0,0,0,0,0,0,0,3,1,21,27,0,0,0,0
26,27,0,0,0,0,0,0,0,0,1,2,5,4,0,0,0,0
27,28,0,0,0,0,0,0,0,0,46,53,0,1,0,1,0,0
28,29,0,0,0,0,0,0,0,0,175,159,25,18,66,47,0,0
29,30,0,0,0,0,0,0,0,0,67,67,191,127,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,0,0,46,47,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [118]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        0.0
5月_オス        0.0
6月_メス        0.0
6月_オス        0.0
7月_メス        0.0
7月_オス        0.0
8月_メス      397.0
8月_オス      383.0
9月_メス     2411.0
9月_オス     2157.0
10月_メス     930.0
10月_オス     835.0
11月_メス      19.0
11月_オス      16.0
dtype: float64

## CSVとして保存

In [119]:
df.to_csv("トビイロウンカ日別誘殺数_2020.csv")

# 2020_ヒメトビウンカ日別誘殺数

## tabulaによる表の抽出

In [184]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2020.pdf",
    pages = '81',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0, 3], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

new_values = [
    "6\r7\r8\r9\r10",
    "0\r0\r0\r0\r0", "0\r0\r0\r0\r0",            # 4月
    "0\r0\r0\r0\r0", "0\r0\r0\r0\r0",            # 5月
    "12\r0\r1\r0\r1", "0\r0\r1\r1\r1",           # 6月
    "2\r0\r0\r0\r0", "0\r1\r0\r0\r2",            # 7月
    "64\r77\r102\r25\r21", "56\r46\r54\r25\r11", # 8月
    "25\r9\r8\r11\r12", "22\r11\r0\r0\r3",       # 9月
    "0\r0\r1\r1\r2", "1\r0\r1\r0\r1",            # 10月
    "0\r0\r0\r0\r0", "0\r0\r0\r0\r0"             # 11月
    ]
df.iloc[1] = new_values

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r1\r1\r4\r2,0\r0\r1\r4\r2,0\r0\r1\r0\r0,0\r0\r0\r0\r0,191\r104\r198\r109\r45,86\r15\r99\r49\r15,6\r42\r300\r21\r30,4\r23\r90\r8\r16,1\r0\r0\r6\r0,0\r0\r0\r5\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,12\r0\r1\r0\r1,0\r0\r1\r1\r1,2\r0\r0\r0\r0,0\r1\r0\r0\r2,64\r77\r102\r25\r21,56\r46\r54\r25\r11,25\r9\r8\r11\r12,22\r11\r0\r0\r3,0\r0\r1\r1\r2,1\r0\r1\r0\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,2\r2\r0\r0\r2,0\r0\r0\r0\r0,0\r0\r4\r1\r3,0\r0\r18\r4\r2,9\r47\r35\r13\r39,9\r40\r19\r14\r32,3\r8\r1\r0\r1,2\r0\r1\r0\r0,1\r0\r0\r0\r0,2\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r3\r5\r2,1\r1\r2\r0\r1,51\r88\r53\r56\r39,18\r41\r25\r28\r45,23\r26\r1\r11\r3,7\r10\r0\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r15\r1\r1\r1,1\r6\r0\r1\r1,13\r13\r67\r21\r189,11\r18\r27\r9\r138,0\r0\r0\r0\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
7,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r1\r0,0\r0\r0\r0\r3\r0,0\r0\r0\r2\r0,0\r0\r0\r0\r0,0\r0\r3\r0\r14\r18,0\r0\r0\r0\r0\r6,22\r9\r116\r116\r116\r46,7\r6\r47\r83\r36\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [186]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,191,86,6,4,1,0,0,0
1,2,0,0,0,0,1,0,0,0,104,15,42,23,0,0,0,0
2,3,0,0,0,0,1,1,1,0,198,99,300,90,0,0,0,0
3,4,0,0,0,0,4,4,0,0,109,49,21,8,6,5,0,0
4,5,0,0,0,0,2,2,0,0,45,15,30,16,0,0,0,0
5,6,0,0,0,0,12,0,2,0,64,56,25,22,0,1,0,0
6,7,0,0,0,0,0,0,0,1,77,46,9,11,0,0,0,0
7,8,0,0,0,0,1,1,0,0,102,54,8,0,1,1,0,0
8,9,0,0,0,0,0,1,0,0,25,25,11,0,1,0,0,0
9,10,0,0,0,0,1,1,0,2,21,11,12,3,2,1,0,0
10,11,0,0,0,0,2,0,0,0,9,9,3,2,1,2,0,0
11,12,0,0,0,0,2,0,0,0,47,40,8,0,0,0,0,0
12,13,0,0,0,0,0,0,4,18,35,19,1,1,0,0,0,0
13,14,0,0,0,0,0,0,1,4,13,14,0,0,0,0,0,0
14,15,0,0,0,0,2,0,3,2,39,32,1,0,0,0,0,0
15,16,0,0,0,0,0,0,0,1,51,18,23,7,0,0,0,0
16,17,0,0,0,0,0,0,0,1,88,41,26,10,0,0,0,0
17,18,0,0,0,0,0,0,3,2,53,25,1,0,0,0,0,0
18,19,0,0,0,0,0,0,5,0,56,28,11,1,0,0,0,0
19,20,0,0,0,0,0,0,2,1,39,45,3,0,0,0,0,0
20,21,0,0,0,0,0,0,0,1,13,11,0,0,0,0,0,0
21,22,0,0,0,0,0,0,15,6,13,18,0,0,0,0,0,0
22,23,0,0,0,0,0,0,1,0,67,27,0,0,0,0,0,0
23,24,0,0,0,0,0,0,1,1,21,9,0,0,0,0,0,0
24,25,0,0,0,1,0,0,1,1,189,138,1,0,0,0,0,0
25,26,0,0,0,0,0,0,0,0,22,7,0,0,0,0,0,0
26,27,0,0,0,0,0,0,0,0,9,6,0,0,0,0,0,0
27,28,0,0,0,0,0,0,3,0,116,47,0,0,0,0,0,0
28,29,0,0,0,0,2,0,0,0,116,83,0,0,0,0,0,0
29,30,0,0,1,3,0,0,14,0,116,36,0,0,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,18,6,46,25,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [187]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        1.0
5月_オス        4.0
6月_メス       30.0
6月_オス       10.0
7月_メス       74.0
7月_オス       47.0
8月_メス     2094.0
8月_オス     1134.0
9月_メス      542.0
9月_オス      198.0
10月_メス      12.0
10月_オス      10.0
11月_メス       0.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [ ]:
df.to_csv("ヒメトビウンカ日別誘殺数_2020.csv")

# 2021_セジロウンカ日別誘殺数

## tabulaによる表の抽出

In [144]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2021.pdf",
    pages = '79',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r2\r0\r0\r1,0\r2\r0\r0\r1,6\r27\r8\r2\r2,2\r11\r8\r4\r0,168\r626\r131\r167\r74,231\r803\r135\r256\r59,0\r0\r0\r0\r2,1\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r3\r9,1\r0\r1\r2\r3,1\r7\r0\r2\r25,4\r5\r0\r2\r15,6\r183\r163\r45\r106,9\r287\r223\r69\r122,0\r6\r0\r4\r3,0\r8\r1\r4\r3,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,3\r0\r3\r0\r0,5\r0\r0\r0\r0,46\r24\r147\r72\r31,43\r14\r90\r41\r10,25\r101\r127\r11\r24,31\r138\r118\r23\r38,0\r18\r7\r11\r30,1\r14\r7\r5\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,99\r37\r32\r9\r5,64\r28\r25\r3\r4,19\r7\r8\r3\r6,36\r3\r11\r8\r4,7\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,12\r123\r1\r5\r2,1\r66\r0\r4\r3,2\r2\r8\r4\r7,4\r6\r12\r2\r4,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r1\r1\r1\r2\r0,0\r0\r2\r0\r0\r0,17\r7\r5\r5\r11\r36,16\r3\r4\r5\r14\r37,1\r2\r1\r1\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [145]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,6,2,168,231,0,1,0,0
1,2,0,0,0,0,0,0,2,2,27,11,626,803,0,0,0,0
2,3,0,0,0,0,0,0,0,0,8,8,131,135,0,0,0,0
3,4,0,0,0,0,0,0,0,0,2,4,167,256,0,0,0,0
4,5,0,0,0,0,0,0,1,1,2,0,74,59,2,0,0,0
5,6,0,0,0,0,0,0,0,1,1,4,6,9,0,0,0,0
6,7,0,0,0,0,0,0,0,0,7,5,183,287,6,8,0,0
7,8,0,0,0,0,0,0,2,1,0,0,163,223,0,1,0,0
8,9,0,0,0,0,0,0,3,2,2,2,45,69,4,4,0,0
9,10,0,0,0,0,0,0,9,3,25,15,106,122,3,3,0,0
10,11,0,0,0,0,0,0,3,5,46,43,25,31,0,1,0,0
11,12,0,0,0,0,0,0,0,0,24,14,101,138,18,14,0,0
12,13,0,0,0,0,0,0,3,0,147,90,127,118,7,7,0,0
13,14,0,0,0,0,0,0,0,0,72,41,11,23,11,5,0,0
14,15,0,0,0,0,0,0,0,0,31,10,24,38,30,20,0,0
15,16,0,0,0,0,0,0,1,0,99,64,19,36,7,1,0,0
16,17,0,0,0,0,0,0,0,0,37,28,7,3,0,0,0,0
17,18,0,0,0,0,0,0,0,0,32,25,8,11,0,0,0,0
18,19,0,0,0,0,0,0,0,0,9,3,3,8,0,0,0,0
19,20,0,0,0,0,0,0,0,0,5,4,6,4,0,0,0,0
20,21,0,0,0,0,0,0,0,0,12,1,2,4,0,0,0,0
21,22,0,0,0,0,0,0,0,0,123,66,2,6,0,0,0,0
22,23,0,0,0,0,0,0,0,0,1,0,8,12,0,0,0,0
23,24,0,0,0,0,0,0,0,0,5,4,4,2,0,0,0,0
24,25,0,0,0,0,0,0,0,0,2,3,7,4,0,0,0,0
25,26,0,0,0,0,0,0,1,0,17,16,1,1,0,0,0,0
26,27,0,0,0,0,0,0,1,0,7,3,2,0,0,0,0,0
27,28,0,0,0,0,0,0,1,2,5,4,1,0,0,0,0,0
28,29,0,0,0,0,0,0,1,0,5,5,1,0,0,0,0,0
29,30,0,0,0,0,0,0,2,0,11,14,0,0,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,0,0,36,37,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [146]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        0.0
5月_オス        0.0
6月_メス        0.0
6月_オス        0.0
7月_メス       30.0
7月_オス       17.0
8月_メス      806.0
8月_オス      526.0
9月_メス     2028.0
9月_オス     2633.0
10月_メス      88.0
10月_オス      65.0
11月_メス       0.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [147]:
df.to_csv("セジロウンカ日別誘殺数_2021.csv")

# 2021_トビイロウンカ日別誘殺数

## tabulaによる表の抽出

In [148]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2021.pdf",
    pages = '80',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r1\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r1\r3,0\r0\r0\r0\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,2\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r1\r0\r0,0\r0\r2\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [149]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,13,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
13,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,23,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0
23,24,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
24,25,0,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0
25,26,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
26,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,28,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0
28,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,0,0,0,0,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [150]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       0.0
6月_オス       0.0
7月_メス       0.0
7月_オス       0.0
8月_メス       4.0
8月_オス       0.0
9月_メス       8.0
9月_オス       3.0
10月_メス      0.0
10月_オス      0.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

## CSVとして保存

In [151]:
df.to_csv("トビイロウンカ日別誘殺数_2021.csv")

# 2021_ヒメトビウンカ日別誘殺数

## tabulaによる表の抽出

In [152]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2021.pdf",
    pages = '81',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
1,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r1\r0\r0\r0,0\r1\r1\r0\r0,0\r13\r1\r0\r10,3\r10\r0\r3\r33,11\r46\r30\r10\r2,4\r19\r16\r9\r4,96\r17\r5\r30\r25,115\r5\r9\r20\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
2,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r2\r1\r0\r0,1\r0\r1\r0\r0,14\r4\r14\r5\r4,10\r4\r2\r3\r2,29\r32\r0\r6\r56,17\r17\r0\r6\r29,0\r18\r15\r2\r31,1\r11\r13\r6\r18,2\r3\r0\r1\r2,1\r2\r0\r2\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,2\r1\r0\r0\r3,0\r0\r0\r0\r0,2\r0\r3\r3\r1,1\r1\r4\r1\r0,56\r21\r265\r231\r20,45\r22\r154\r119\r3,14\r51\r24\r11\r7,15\r27\r15\r23\r2,3\r1\r23\r1\r3,0\r1\r9\r1\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r1\r0\r0\r0,0\r4\r1\r0\r0,2\r7\r0\r0\r0,66\r45\r12\r10\r0,47\r39\r2\r13\r4,7\r7\r5\r3\r1,15\r4\r7\r1\r2,0\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r0\r2\r0\r0,0\r0\r0\r0\r0,12\r54\r7\r22\r12,7\r39\r3\r14\r6,5\r0\r15\r2\r3,1\r1\r2\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r1,0\r0\r0\r3\r5,0\r0\r1\r0\r2,1\r12\r7\r32\r7\r6,0\r6\r3\r15\r9\r3,16\r9\r7\r7\r9\r20,15\r5\r15\r2\r7\r8,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [153]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,3,11,4,96,115,0,0,0,0
1,2,0,0,0,0,1,1,13,10,46,19,17,5,0,0,0,0
2,3,0,0,0,0,0,1,1,0,30,16,5,9,0,0,0,0
3,4,0,0,0,0,0,0,0,3,10,9,30,20,0,0,0,0
4,5,0,0,0,0,0,0,10,33,2,4,25,10,0,0,0,0
5,6,0,0,0,0,1,1,14,10,29,17,0,1,2,1,0,0
6,7,0,0,0,0,2,0,4,4,32,17,18,11,3,2,0,0
7,8,0,0,0,0,1,1,14,2,0,0,15,13,0,0,0,0
8,9,0,0,0,0,0,0,5,3,6,6,2,6,1,2,0,0
9,10,0,0,0,0,0,0,4,2,56,29,31,18,2,0,0,0
10,11,0,0,0,0,2,0,2,1,56,45,14,15,3,0,0,0
11,12,0,0,0,0,1,0,0,1,21,22,51,27,1,1,0,0
12,13,0,0,0,0,0,0,3,4,265,154,24,15,23,9,0,0
13,14,0,0,0,0,0,0,3,1,231,119,11,23,1,1,0,0
14,15,0,0,0,0,3,0,1,0,20,3,7,2,3,1,0,0
15,16,0,0,0,0,0,0,0,2,66,47,7,15,0,1,0,0
16,17,0,0,0,0,0,1,4,7,45,39,7,4,0,0,0,0
17,18,0,0,0,0,0,0,1,0,12,2,5,7,0,0,0,0
18,19,0,0,0,0,0,0,0,0,10,13,3,1,0,0,0,0
19,20,0,0,0,0,0,0,0,0,0,4,1,2,0,0,0,0
20,21,0,0,0,0,0,0,1,0,12,7,5,1,0,0,0,0
21,22,0,0,0,0,0,0,0,0,54,39,0,1,0,0,0,0
22,23,0,0,0,0,0,0,2,0,7,3,15,2,0,0,0,0
23,24,0,0,0,0,0,0,0,0,22,14,2,1,0,0,0,0
24,25,0,0,0,0,0,0,0,0,12,6,3,0,0,0,0,0
25,26,0,0,0,0,0,0,1,0,16,15,0,0,0,0,0,0
26,27,0,0,0,0,0,0,12,6,9,5,0,0,0,0,0,0
27,28,0,0,0,0,0,1,7,3,7,15,0,0,0,0,0,0
28,29,0,0,0,0,3,0,32,15,7,2,0,0,0,0,0,0
29,30,0,0,0,0,5,2,7,9,9,7,0,0,0,0,0,0
30,31,NaN,NaN,0,1,NaN,NaN,6,3,20,8,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [154]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        0.0
5月_オス        1.0
6月_メス       19.0
6月_オス        8.0
7月_メス      147.0
7月_オス      122.0
8月_メス     1123.0
8月_オス      690.0
9月_メス      394.0
9月_オス      324.0
10月_メス      39.0
10月_オス      18.0
11月_メス       0.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [155]:
df.to_csv("ヒメトビウンカ日別誘殺数_2021.csv")

# 2022_セジロウンカ日別誘殺数

## tabulaによる表の抽出

In [173]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2022.pdf",
    pages = '78',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0, 1, 2, 13, 24], inplace=True)
df.drop(['Unnamed: 4', 'Unnamed: 6'], axis=1, inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df[['8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス']] = np.nan

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 10:10:29 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Sep 16, 2025 10:10:29 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
3,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,6,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,8,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,9,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,11,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,12,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,13,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,14,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,15,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,16,0,0,0,0,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17,0,0,0,0,0,0,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,18,0,0,0,0,0,0,9,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,19,0,0,0,0,0,0,14,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,20,0,0,0,0,0,0,10,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,21,0,0,0,0,0,0,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,22,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,23,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,24,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,25,0,0,0,0,0,0,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,26,0,0,0,0,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,27,0,0,0,0,0,0,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,28,0,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,29,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,30,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,31,NaN,NaN,0,0,NaN,NaN,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 誤記チェック（4〜7月）

In [174]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       0.0
6月_オス       0.0
7月_メス      50.0
7月_オス      25.0
8月_メス       0.0
8月_オス       0.0
9月_メス       0.0
9月_オス       0.0
10月_メス      0.0
10月_オス      0.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

In [176]:
df['8月_メス'] = [0, 0, 3, 11, 21, 5, 51, 7, 2, 38, 7, 17, 74, 46, 10, 17, 12, 64, 119, 395, 95, 10, 79, 66, 55, 10, 33, 5, 38, 7, 19]
df['8月_オス'] = [0, 0, 2, 7, 23, 3, 28, 0, 2, 14, 2, 28, 146, 41, 14, 10, 4, 67, 127, 264, 76, 6, 41, 83, 67, 5, 51, 5, 37, 8, 14]
df['9月_メス'] = [9, 23, 25, 9, 6, 35, 32, 100, 31, 41, 23, 2, 8, 2, 7, 4, 0, 2, 1, 0, 0, 39, 18, 2, 0, 33, 28, 20, 0, 1, np.nan]
df['9月_オス'] = [5, 20, 21, 8, 7, 42, 29, 57, 24, 45, 19, 13, 17, 6, 9, 5, 0, 2, 4, 0, 0, 44, 16, 2, 0, 31, 23, 17, 1, 1, np.nan]
df['10月_メス'] = [0, 1, 8, 25, 4, 5, 1, 1, 4, 1, 1, 0, 0, 1, 0, 11, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
df['10月_オス'] = [1, 1, 4, 14, 10, 3, 0, 1, 4, 3, 1, 0, 1, 1, 0, 11, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
df['11月_メス'] = [0] * 30 + [np.nan]
df['11月_オス'] = [0] * 30 + [np.nan]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,9.0,5.0,0,1,0.0,0.0
4,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,23.0,20.0,1,1,0.0,0.0
5,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,2,25.0,21.0,8,4,0.0,0.0
6,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11,7,9.0,8.0,25,14,0.0,0.0
7,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,23,6.0,7.0,4,10,0.0,0.0
8,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,3,35.0,42.0,5,3,0.0,0.0
9,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51,28,32.0,29.0,1,0,0.0,0.0
10,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,0,100.0,57.0,1,1,0.0,0.0
11,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2,31.0,24.0,4,4,0.0,0.0
12,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38,14,41.0,45.0,1,3,0.0,0.0
14,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,2,23.0,19.0,1,1,0.0,0.0
15,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,28,2.0,13.0,0,0,0.0,0.0
16,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74,146,8.0,17.0,0,1,0.0,0.0
17,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46,41,2.0,6.0,1,1,0.0,0.0
18,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10,14,7.0,9.0,0,0,0.0,0.0
19,16.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,17,10,4.0,5.0,11,11,0.0,0.0
20,17.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,12,4,0.0,0.0,2,1,0.0,0.0
21,18.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,2.0,64,67,2.0,2.0,0,0,0.0,0.0
22,19.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,9.0,119,127,1.0,4.0,0,0,0.0,0.0
23,20.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,7.0,395,264,0.0,0.0,0,0,0.0,0.0
25,21.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,95,76,0.0,0.0,0,0,0.0,0.0
26,22.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10,6,39.0,44.0,1,1,0.0,0.0
27,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79,41,18.0,16.0,0,0,0.0,0.0
28,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66,83,2.0,2.0,0,0,0.0,0.0
29,25.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,55,67,0.0,0.0,0,0,0.0,0.0
30,26.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,10,5,33.0,31.0,0,0,0.0,0.0
31,27.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,33,51,28.0,23.0,0,0,0.0,0.0
32,28.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5,5,20.0,17.0,0,0,0.0,0.0
33,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38,37,0.0,1.0,0,0,0.0,0.0
34,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,8,1.0,1.0,0,0,0.0,0.0
35,31.0,NaN,NaN,0.0,0.0,NaN,NaN,2.0,0.0,19,14,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [177]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        0.0
5月_オス        0.0
6月_メス        0.0
6月_オス        0.0
7月_メス       50.0
7月_オス       25.0
8月_メス     1316.0
8月_オス     1175.0
9月_メス      501.0
9月_オス      468.0
10月_メス      66.0
10月_オス      57.0
11月_メス       0.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [178]:
df.to_csv("セジロウンカ日別誘殺数_2022.csv")

# 2022_トビイロウンカ日別誘殺数

## tabulaによる表の抽出

In [196]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2022.pdf",
    pages = '79',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0, 1, 2, 13, 24], inplace=True)
df.drop(['Unnamed: 1', 'Unnamed: 3'], axis=1, inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df[df['日'] == '1'] = [1] + [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]
df[df['日'] == '11'] = [11] + ([0] * 8) + [0, 1, 10, 6] + ([0] * 4)
df[df['日'] == '20'] = [20] + ([0] * 8) + [28, 18] + ([0] * 6)
df[df['日'] == '21'] = [21] + ([0] * 8) + [1, 2] + ([0] * 6)

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 10:49:11 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Sep 16, 2025 10:49:12 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
3,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0
4,2,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0.0
5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
6,4,0,0,0,0,0,0,0,0,0,0,0,0,36,36,0,0.0
7,5,0,0,0,0,0,0,0,0,0,0,0,0,8,8,0,0.0
8,6,0,0,0,0,0,0,0,0,0,0,2,0,3,1,0,0.0
9,7,0,0,0,0,0,0,0,0,1,0,2,4,0,0,0,0.0
10,8,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0.0
11,9,0,0,0,0,0,0,0,0,2,2,3,0,0,5,0,0.0
12,10,0,0,0,0,0,0,0,0,4,3,12,6,1,2,0,0.0
14,11,0,0,0,0,0,0,0,0,0,1,10,6,0,0,0,0.0
15,12,0,0,0,0,0,0,0,0,0,1,11,28,0,0,0,0.0
16,13,0,0,0,0,0,0,0,0,1,0,13,22,0,0,0,0.0
17,14,0,0,0,0,0,0,0,0,0,5,5,1,1,0,0,0.0
18,15,0,0,0,0,0,0,0,0,7,4,7,3,0,0,0,0.0
19,16,0,0,0,0,0,0,0,0,2,2,1,0,16,18,0,0.0
20,17,0,0,0,0,0,0,0,0,5,2,0,0,2,1,0,0.0
21,18,0,0,0,0,0,0,0,0,1,3,2,0,0,0,0,0.0
22,19,0,0,0,0,0,0,0,0,2,7,0,1,0,0,0,0.0
23,20,0,0,0,0,0,0,0,0,28,18,0,0,0,0,0,0.0
25,21,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0.0
26,22,0,0,0,0,0,0,0,0,0,0,11,17,1,1,0,0.0
27,23,0,0,0,0,0,0,0,0,1,1,7,11,0,0,0,0.0
28,24,0,0,0,0,0,0,0,0,2,1,0,1,0,0,0,0.0
29,25,0,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0.0
30,26,0,0,0,0,0,0,0,0,1,0,9,8,0,0,0,0.0
31,27,0,0,0,0,0,0,0,0,0,4,3,12,0,0,0,0.0
32,28,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0.0
33,29,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0.0
34,30,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0
35,31,NaN,NaN,0,0,NaN,NaN,0,0,0,0,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [197]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       0.0
6月_オス       0.0
7月_メス       0.0
7月_オス       0.0
8月_メス      59.0
8月_オス      61.0
9月_メス     107.0
9月_オス     130.0
10月_メス     69.0
10月_オス     72.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

## CSVとして保存

In [198]:
df.to_csv("トビイロウンカ日別誘殺数_2022.csv")

# 2022_ヒメトビウンカ日別誘殺数

## tabulaによる表の抽出

In [200]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2022.pdf",
    pages = '80',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]

df.drop([0, 1, 2, 13, 24], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 10:51:50 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Sep 16, 2025 10:51:50 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
3,1,0,0,0,0,0,0,3,1,5,6,6,2,1,0,0,0
4,2,0,0,0,0,0,0,20,19,16,8,19,5,0,0,0,0
5,3,0,0,0,0,10,0,36,11,81,27,24,4,0,0,0,0
6,4,0,0,0,0,0,0,15,3,138,69,10,7,9,2,0,0
7,5,0,0,0,0,0,0,2,0,72,54,21,8,4,0,0,0
8,6,0,0,0,0,0,0,9,2,70,45,23,18,1,0,0,0
9,7,0,0,0,0,0,0,5,2,86,48,12,5,1,0,0,0
10,8,0,0,0,0,0,0,2,4,36,15,39,34,0,0,0,0
11,9,0,0,0,0,0,0,4,2,25,15,15,10,0,1,0,0
12,10,0,0,0,0,1,0,5,2,240,90,13,9,0,0,0,0
14,11,0,0,0,0,0,0,3,1,28,6,19,12,0,0,0,0
15,12,0,0,0,0,0,0,3,1,76,66,9,3,0,0,0,0
16,13,0,0,0,0,0,0,1,0,36,14,24,9,0,0,0,0
17,14,0,0,0,0,0,0,1,0,56,38,5,7,0,0,0,0
18,15,0,0,0,0,0,0,0,1,57,29,5,5,0,0,0,0
19,16,0,0,0,0,0,0,7,0,9,10,0,0,3,0,0,0
20,17,0,0,0,0,1,0,4,0,16,3,2,0,0,0,0,0
21,18,0,0,0,0,0,0,3,2,18,10,5,5,0,0,0,0
22,19,0,0,0,0,0,0,4,1,60,40,0,0,0,0,0,0
23,20,0,0,0,0,2,1,0,0,68,48,1,1,0,0,0,0
25,21,0,0,0,0,0,0,0,0,19,14,0,1,0,0,0,0
26,22,0,0,0,0,0,0,0,0,2,4,5,4,0,0,0,0
27,23,0,0,0,0,2,0,0,0,33,30,2,8,0,0,0,0
28,24,0,0,0,0,0,2,2,0,27,9,0,0,0,0,0,0
29,25,0,0,0,0,0,0,0,1,33,23,0,0,0,0,0,0
30,26,0,0,0,0,1,0,2,1,10,6,5,3,0,0,0,0
31,27,0,0,0,0,0,0,0,0,29,14,3,0,0,0,0,0
32,28,0,0,1,3,0,0,5,1,0,0,1,1,0,0,0,0
33,29,0,0,0,0,0,0,7,4,33,12,0,0,0,0,0,0
34,30,0,0,0,0,3,2,14,2,6,1,0,0,0,0,0,0
35,31,NaN,NaN,0,0,NaN,NaN,57,34,118,54,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [201]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日          496.0
4月_メス        0.0
4月_オス        0.0
5月_メス        1.0
5月_オス        3.0
6月_メス       20.0
6月_オス        5.0
7月_メス      214.0
7月_オス       95.0
8月_メス     1503.0
8月_オス      808.0
9月_メス      268.0
9月_オス      161.0
10月_メス      19.0
10月_オス       3.0
11月_メス       0.0
11月_オス       0.0
dtype: float64

## CSVとして保存

In [202]:
df.to_csv("ヒメトビウンカ日別誘殺数_2022.csv")

# 2023_セジロウンカ日別誘殺数

## tabulaによる表の抽出

In [231]:
df = pd.DataFrame(
    columns = [
        '日',
        '4月_メス', '4月_オス',
        '5月_メス', '5月_オス',
        '6月_メス', '6月_オス',
        '7月_メス', '7月_オス',
        '8月_メス', '8月_オス',
        '9月_メス', '9月_オス',
        '10月_メス', '10月_オス',
        '11月_メス', '11月_オス'
        ]
    )

df['日'] = range(1, 31 + 1)
df['4月_メス'] = ([0] * 30) + [np.nan]
df['4月_オス'] = ([0] * 30) + [np.nan]
df['5月_メス'] = [0] * 31
df['5月_オス'] = [0] * 31
df['6月_メス'] = ([0] * 27) + [1, 1, 0] + [np.nan]
df['6月_オス'] = ([0] * 30) + [np.nan]
df['7月_メス'] = [3, 2, 0, 0, 7, 0, 1, 9, 4, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 2]
df['7月_オス'] = [1, 1, 0, 0, 11, 0, 0, 4, 6, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 6]
df['8月_メス'] = [1, 1, 0, 0, 2, 1, 4, 0, 1, 3, 1, 6, 1, 2, 0, 8, 25, 2, 1, 2, 5, 0, 0, 0, 0, 1, 3, '欠測', '欠測', '欠測', '欠測']
df['8月_オス'] = [1, 0, 1, 0, 1, 0, 3, 0, 1, 1, 0, 4, 2, 9, 1, 1, 3, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, '欠測', '欠測', '欠測', '欠測']
df['9月_メス'] = ['欠測', '欠測', '欠測', '欠測', '欠測', '欠測', '欠測', 3, 2, 7, 0, 0, 0, 3, 3, 1, 0, 1, 1, 3, 33, 7, 1, 2, 0, 2, 7, 25, 2, 24, np.nan]
df['9月_オス'] = ['欠測', '欠測', '欠測', '欠測', '欠測', '欠測', '欠測', 4, 3, 9, 1, 0, 0, 3, 2, 0, 0, 0, 2, 3, 55, 8, 0, 3, 0, 1, 3, 21, 7, 24, np.nan]
df['10月_メス'] = [6, 1, 2, 18, 0, 0, 0, 0, 1, 2, 1] + ([0] * 20)
df['10月_オス'] = [6, 1, 1, 22, 0, 0, 0, 0, 1, 0] + ([0] * 21)
df['11月_メス'] = ([0] * 30) + [np.nan]
df['11月_オス'] = [0, 1, 0, 0, 0, 0, 1, 0, 0, 0] + ([0] * 20) + [np.nan]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0.0,0.0,0,0,0.0,0.0,3,1,1,1,欠測,欠測,6,6,0.0,0.0
1,2,0.0,0.0,0,0,0.0,0.0,2,1,1,0,欠測,欠測,1,1,0.0,1.0
2,3,0.0,0.0,0,0,0.0,0.0,0,0,0,1,欠測,欠測,2,1,0.0,0.0
3,4,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,18,22,0.0,0.0
4,5,0.0,0.0,0,0,0.0,0.0,7,11,2,1,欠測,欠測,0,0,0.0,0.0
5,6,0.0,0.0,0,0,0.0,0.0,0,0,1,0,欠測,欠測,0,0,0.0,0.0
6,7,0.0,0.0,0,0,0.0,0.0,1,0,4,3,欠測,欠測,0,0,0.0,1.0
7,8,0.0,0.0,0,0,0.0,0.0,9,4,0,0,3,4,0,0,0.0,0.0
8,9,0.0,0.0,0,0,0.0,0.0,4,6,1,1,2,3,1,1,0.0,0.0
9,10,0.0,0.0,0,0,0.0,0.0,1,0,3,1,7,9,2,0,0.0,0.0
10,11,0.0,0.0,0,0,0.0,0.0,0,0,1,0,0,1,1,0,0.0,0.0
11,12,0.0,0.0,0,0,0.0,0.0,0,0,6,4,0,0,0,0,0.0,0.0
12,13,0.0,0.0,0,0,0.0,0.0,1,0,1,2,0,0,0,0,0.0,0.0
13,14,0.0,0.0,0,0,0.0,0.0,0,2,2,9,3,3,0,0,0.0,0.0
14,15,0.0,0.0,0,0,0.0,0.0,0,0,0,1,3,2,0,0,0.0,0.0
15,16,0.0,0.0,0,0,0.0,0.0,0,0,8,1,1,0,0,0,0.0,0.0
16,17,0.0,0.0,0,0,0.0,0.0,0,0,25,3,0,0,0,0,0.0,0.0
17,18,0.0,0.0,0,0,0.0,0.0,0,0,2,2,1,0,0,0,0.0,0.0
18,19,0.0,0.0,0,0,0.0,0.0,0,1,1,0,1,2,0,0,0.0,0.0
19,20,0.0,0.0,0,0,0.0,0.0,0,0,2,2,3,3,0,0,0.0,0.0
20,21,0.0,0.0,0,0,0.0,0.0,1,0,5,1,33,55,0,0,0.0,0.0
21,22,0.0,0.0,0,0,0.0,0.0,0,0,0,0,7,8,0,0,0.0,0.0
22,23,0.0,0.0,0,0,0.0,0.0,0,0,0,0,1,0,0,0,0.0,0.0
23,24,0.0,0.0,0,0,0.0,0.0,1,0,0,0,2,3,0,0,0.0,0.0
24,25,0.0,0.0,0,0,0.0,0.0,1,0,0,0,0,0,0,0,0.0,0.0
25,26,0.0,0.0,0,0,0.0,0.0,1,1,1,0,2,1,0,0,0.0,0.0
26,27,0.0,0.0,0,0,0.0,0.0,0,0,3,0,7,3,0,0,0.0,0.0
27,28,0.0,0.0,0,0,1.0,0.0,1,0,欠測,欠測,25,21,0,0,0.0,0.0
28,29,0.0,0.0,0,0,1.0,0.0,0,3,欠測,欠測,2,7,0,0,0.0,0.0
29,30,0.0,0.0,0,0,0.0,0.0,0,0,欠測,欠測,24,24,0,0,0.0,0.0
30,31,NaN,NaN,0,0,NaN,NaN,2,6,欠測,欠測,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [232]:
df_check = df.copy()
df_check = df_check.replace('欠測', np.nan)
df_check = df_check.astype('float64') # object -> float64
# print(df.dtypes)

df_check.sum()

/tmp/ipython-input-4283373825.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_check = df_check.replace('欠測', np.nan)

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       2.0
6月_オス       0.0
7月_メス      35.0
7月_オス      36.0
8月_メス      70.0
8月_オス      33.0
9月_メス     127.0
9月_オス     149.0
10月_メス     31.0
10月_オス     31.0
11月_メス      0.0
11月_オス      2.0
dtype: float64

## CSVとして保存

In [233]:
df.to_csv("セジロウンカ日別誘殺数_2023.csv")

# 2023_トビイロウンカ日別誘殺数

## tabulaによる表の抽出

In [228]:
df = pd.DataFrame(
    columns = [
        '日',
        '4月_メス', '4月_オス',
        '5月_メス', '5月_オス',
        '6月_メス', '6月_オス',
        '7月_メス', '7月_オス',
        '8月_メス', '8月_オス',
        '9月_メス', '9月_オス',
        '10月_メス', '10月_オス',
        '11月_メス', '11月_オス'
        ]
    )

df['日'] = range(1, 31 + 1)
df['4月_メス'] = ([0] * 30) + [np.nan]
df['4月_オス'] = ([0] * 30) + [np.nan]
df['5月_メス'] = [0] * 31
df['5月_オス'] = [0] * 31
df['6月_メス'] = ([0] * 30) + [np.nan]
df['6月_オス'] = ([0] * 30) + [np.nan]
df['7月_メス'] = [0] * 31
df['7月_オス'] = [0] * 31
df['8月_メス'] = ([0] * 13) + [1] + ([0] * 13) + (['欠測'] * 4)
df['8月_オス'] = ([0] * 27) + (['欠測'] * 4)
df['9月_メス'] = (['欠測'] * 7) + ([0] * 12) + [1, 5, 2, 0, 0, 0, 0, 10, 64, 5, 75, np.nan]
df['9月_オス'] = (['欠測'] * 7) + ([0] * 13) + [4, 0, 0, 0, 0, 1, 20, 96, 12, 63, np.nan]
df['10月_メス'] = [11, 1, 4, 3, 0] + ([0] * 26)
df['10月_オス'] = [16, 1, 3, 5, 2] + ([0] * 26)
df['11月_メス'] = ([0] * 30) + [np.nan]
df['11月_オス'] = ([0] * 30) + [np.nan]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,11,16,0.0,0.0
1,2,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,1,1,0.0,0.0
2,3,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,4,3,0.0,0.0
3,4,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,3,5,0.0,0.0
4,5,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,0,2,0.0,0.0
5,6,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,0,0,0.0,0.0
6,7,0.0,0.0,0,0,0.0,0.0,0,0,0,0,欠測,欠測,0,0,0.0,0.0
7,8,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
8,9,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
9,10,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
10,11,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
11,12,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
12,13,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
13,14,0.0,0.0,0,0,0.0,0.0,0,0,1,0,0,0,0,0,0.0,0.0
14,15,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
15,16,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
16,17,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
17,18,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
18,19,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
19,20,0.0,0.0,0,0,0.0,0.0,0,0,0,0,1,0,0,0,0.0,0.0
20,21,0.0,0.0,0,0,0.0,0.0,0,0,0,0,5,4,0,0,0.0,0.0
21,22,0.0,0.0,0,0,0.0,0.0,0,0,0,0,2,0,0,0,0.0,0.0
22,23,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
23,24,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
24,25,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0
25,26,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,1,0,0,0.0,0.0
26,27,0.0,0.0,0,0,0.0,0.0,0,0,0,0,10,20,0,0,0.0,0.0
27,28,0.0,0.0,0,0,0.0,0.0,0,0,欠測,欠測,64,96,0,0,0.0,0.0
28,29,0.0,0.0,0,0,0.0,0.0,0,0,欠測,欠測,5,12,0,0,0.0,0.0
29,30,0.0,0.0,0,0,0.0,0.0,0,0,欠測,欠測,75,63,0,0,0.0,0.0
30,31,NaN,NaN,0,0,NaN,NaN,0,0,欠測,欠測,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [229]:
df_check = df.copy()
df_check = df_check.replace('欠測', np.nan)
df_check = df_check.astype('float64') # object -> float64
# print(df.dtypes)

df_check.sum()

/tmp/ipython-input-4283373825.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_check = df_check.replace('欠測', np.nan)

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       0.0
6月_オス       0.0
7月_メス       0.0
7月_オス       0.0
8月_メス       1.0
8月_オス       0.0
9月_メス     162.0
9月_オス     196.0
10月_メス     19.0
10月_オス     27.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

## CSVとして保存

In [230]:
df.to_csv("トビイロウンカ日別誘殺数_2023.csv")

# 2023_ヒメトビウンカ日別誘殺数

## tabulaによる表の抽出

In [234]:
df = pd.DataFrame(
    columns = [
        '日',
        '4月_メス', '4月_オス',
        '5月_メス', '5月_オス',
        '6月_メス', '6月_オス',
        '7月_メス', '7月_オス',
        '8月_メス', '8月_オス',
        '9月_メス', '9月_オス',
        '10月_メス', '10月_オス',
        '11月_メス', '11月_オス'
        ]
    )

df['日'] = range(1, 31 + 1)
df['4月_メス'] = ([0] * 30) + [np.nan]
df['4月_オス'] = ([0] * 30) + [np.nan]
df['5月_メス'] = ([0] * 25) + [1, 0, 3, 11, 1, 1]
df['5月_オス'] = ([0] * 25) + [0, 0, 1, 2, 5, 0]
df['6月_メス'] = [9, 0, 1, 1, 1, 0, 0, 0, 0, 7, 0, 4, 0, 2, 0, 0, 3, 0, 0, 0, 1, 0, 1, 0, 6, 0, 2, 3, 2, 0, np.nan]
df['6月_オス'] = [3, 0, 0, 2, 1, 0, 0, 0, 0, 6, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, np.nan]
df['7月_メス'] = [0, 0, 3, 0, 1, 2, 3, 13, 7, 0, 1, 0, 6, 0, 0, 0, 3, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 2, 6, 3, 5]
df['7月_オス'] = [0, 0, 3, 1, 4, 2, 2, 13, 7, 3, 0, 0, 3, 11, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 3, 1, 1, 9, 1, 23]
df['8月_メス'] = [6, 7, 0, 5, 40, 0, 0, 4, 7, 2, 12, 2, 7, 17, 5, 2, 23, 2, 0, 1, 1, 0, 0, 5, 4, 2, 19] + (['欠測'] * 4)
df['8月_オス'] = [8, 8, 2, 7, 13, 2, 3, 0, 12, 9, 20, 3, 12, 45, 8, 0, 8, 1, 0, 0, 2, 1, 0, 0, 0, 1, 4] + (['欠測'] * 4)
df['9月_メス'] = (['欠測'] * 7) + [5, 5, 6, 0, 1, 0, 3, 2, 0, 0, 1, 4, 1, 9, 1, 0, 1, 5, 1, 1, 4, 0, 2, np.nan]
df['9月_オス'] = (['欠測'] * 7) + [2, 3, 2, 1, 2, 0, 2, 4, 4, 2, 3, 6, 2, 19, 1, 0, 1, 0, 2, 1, 5, 0, 8, np.nan]
df['10月_メス'] = ([0] * 18) + [1, 0, 0, 1] + ([0] * 9)
df['10月_オス'] = [1, 0, 1, 1, 0] + ([0] * 15) + [0, 1] + ([0] * 9)
df['11月_メス'] = ([0] * 30) + [np.nan]
df['11月_オス'] = ([0] * 18) + [1] + ([0] * 11) + [np.nan]

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0.0,0.0,0,0,9.0,3.0,0,0,6,8,欠測,欠測,0,1,0.0,0.0
1,2,0.0,0.0,0,0,0.0,0.0,0,0,7,8,欠測,欠測,0,0,0.0,0.0
2,3,0.0,0.0,0,0,1.0,0.0,3,3,0,2,欠測,欠測,0,1,0.0,0.0
3,4,0.0,0.0,0,0,1.0,2.0,0,1,5,7,欠測,欠測,0,1,0.0,0.0
4,5,0.0,0.0,0,0,1.0,1.0,1,4,40,13,欠測,欠測,0,0,0.0,0.0
5,6,0.0,0.0,0,0,0.0,0.0,2,2,0,2,欠測,欠測,0,0,0.0,0.0
6,7,0.0,0.0,0,0,0.0,0.0,3,2,0,3,欠測,欠測,0,0,0.0,0.0
7,8,0.0,0.0,0,0,0.0,0.0,13,13,4,0,5,2,0,0,0.0,0.0
8,9,0.0,0.0,0,0,0.0,0.0,7,7,7,12,5,3,0,0,0.0,0.0
9,10,0.0,0.0,0,0,7.0,6.0,0,3,2,9,6,2,0,0,0.0,0.0
10,11,0.0,0.0,0,0,0.0,2.0,1,0,12,20,0,1,0,0,0.0,0.0
11,12,0.0,0.0,0,0,4.0,1.0,0,0,2,3,1,2,0,0,0.0,0.0
12,13,0.0,0.0,0,0,0.0,0.0,6,3,7,12,0,0,0,0,0.0,0.0
13,14,0.0,0.0,0,0,2.0,0.0,0,11,17,45,3,2,0,0,0.0,0.0
14,15,0.0,0.0,0,0,0.0,0.0,0,1,5,8,2,4,0,0,0.0,0.0
15,16,0.0,0.0,0,0,0.0,0.0,0,1,2,0,0,4,0,0,0.0,0.0
16,17,0.0,0.0,0,0,3.0,0.0,3,1,23,8,0,2,0,0,0.0,0.0
17,18,0.0,0.0,0,0,0.0,0.0,1,0,2,1,1,3,0,0,0.0,0.0
18,19,0.0,0.0,0,0,0.0,0.0,0,1,0,0,4,6,1,0,0.0,1.0
19,20,0.0,0.0,0,0,0.0,0.0,0,0,1,0,1,2,0,0,0.0,0.0
20,21,0.0,0.0,0,0,1.0,1.0,1,1,1,2,9,19,0,0,0.0,0.0
21,22,0.0,0.0,0,0,0.0,1.0,0,0,0,1,1,1,1,1,0.0,0.0
22,23,0.0,0.0,0,0,1.0,1.0,0,0,0,0,0,0,0,0,0.0,0.0
23,24,0.0,0.0,0,0,0.0,0.0,0,1,5,0,1,1,0,0,0.0,0.0
24,25,0.0,0.0,0,0,6.0,2.0,2,0,4,0,5,0,0,0,0.0,0.0
25,26,0.0,0.0,1,0,0.0,0.0,1,3,2,1,1,2,0,0,0.0,0.0
26,27,0.0,0.0,0,0,2.0,1.0,0,1,19,4,1,1,0,0,0.0,0.0
27,28,0.0,0.0,3,1,3.0,0.0,2,1,欠測,欠測,4,5,0,0,0.0,0.0
28,29,0.0,0.0,11,2,2.0,0.0,6,9,欠測,欠測,0,0,0,0,0.0,0.0
29,30,0.0,0.0,1,5,0.0,1.0,3,1,欠測,欠測,2,8,0,0,0.0,0.0
30,31,NaN,NaN,1,0,NaN,NaN,5,23,欠測,欠測,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [235]:
df_check = df.copy()
df_check = df_check.replace('欠測', np.nan)
df_check = df_check.astype('float64') # object -> float64
# print(df.dtypes)

df_check.sum()

/tmp/ipython-input-4283373825.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_check = df_check.replace('欠測', np.nan)

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス      17.0
5月_オス       8.0
6月_メス      43.0
6月_オス      22.0
7月_メス      60.0
7月_オス      93.0
8月_メス     173.0
8月_オス     169.0
9月_メス      52.0
9月_オス      70.0
10月_メス      2.0
10月_オス      4.0
11月_メス      0.0
11月_オス      1.0
dtype: float64

## CSVとして保存

In [236]:
df.to_csv("ヒメトビウンカ日別誘殺数_2023.csv")

# 2024_セジロウンカ日別誘殺数

## tabulaによる表の抽出

In [240]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2024.pdf",
    pages = '94',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]


df.drop([0, 1, 8, 9, 10], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 11:54:27 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
2,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,8\r4\r2\r70\r10,1\r0\r1\r26\r1,4\r0\r5\r3\r9,7\r0\r4\r2\r5,4\r26\r0\r4\r10,1\r21\r1\r1\r7,22\r24\r50\r14\r4,28\r10\r39\r8\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,11\r0\r0\r5\r7,0\r0\r0\r0\r1,6\r5\r3\r35\r4,9\r5\r5\r69\r0,8\r5\r8\r1\r0,12\r3\r7\r3\r0,20\r71\r8\r22\r5,19\r36\r9\r18\r7,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,6\r0\r0\r1\r2,4\r1\r0\r1\r0,3\r4\r9\r13\r17,3\r8\r2\r10\r12,3\r10\r1\r0\r2,0\r11\r2\r2\r2,0\r0\r0\r2\r3,2\r0\r1\r2\r4,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,4\r3\r1\r1\r2,3\r1\r1\r1\r1,13\r5\r31\r24\r14,11\r0\r27\r16\r12,1\r3\r1\r4\r3,0\r3\r1\r1\r1,1\r3\r1\r2\r0,2\r1\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r8\r12\r1,0\r0\r2\r3\r1,3\r4\r1\r10\r1,2\r1\r0\r0\r0,8\r17\r3\r7\r0,2\r7\r1\r6\r0,6\r10\r2\r24\r1,1\r7\r2\r11\r1,1\r5\r0\r0\r0,0\r1\r1\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
7,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,3\r0\r9\r1\r16,0\r0\r4\r0\r2,1\r6\r6\r0\r15\r8,0\r0\r1\r0\r0\r3,0\r0\r1\r0\r97\r2,1\r0\r2\r0\r74\r0,1\r2\r20\r2\r58,2\r0\r15\r1\r74,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [241]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,8,1,4,7,4,1,22,28,0,0
1,2,0,0,0,0,0,0,4,0,0,0,26,21,24,10,0,0
2,3,0,0,0,0,0,0,2,1,5,4,0,1,50,39,0,0
3,4,0,0,0,0,0,0,70,26,3,2,4,1,14,8,0,0
4,5,0,0,0,0,0,0,10,1,9,5,10,7,4,5,0,0
5,6,0,0,0,0,0,0,11,0,6,9,8,12,20,19,0,0
6,7,0,0,0,0,0,0,0,0,5,5,5,3,71,36,0,0
7,8,0,0,0,0,0,0,0,0,3,5,8,7,8,9,0,0
8,9,0,0,0,0,0,0,5,0,35,69,1,3,22,18,0,0
9,10,0,0,0,0,0,0,7,1,4,0,0,0,5,7,0,0
10,11,0,0,0,0,0,0,6,4,3,3,3,0,0,2,0,0
11,12,0,0,0,0,0,0,0,1,4,8,10,11,0,0,0,0
12,13,0,0,0,0,0,0,0,0,9,2,1,2,0,1,0,0
13,14,0,0,0,0,0,0,1,1,13,10,0,2,2,2,0,0
14,15,0,0,0,0,0,0,2,0,17,12,2,2,3,4,0,0
15,16,0,0,0,0,0,0,4,3,13,11,1,0,1,2,0,0
16,17,0,0,0,0,0,0,3,1,5,0,3,3,3,1,0,0
17,18,0,0,0,0,0,0,1,1,31,27,1,1,1,0,0,0
18,19,0,0,0,0,0,0,1,1,24,16,4,1,2,0,0,0
19,20,0,0,0,0,0,0,2,1,14,12,3,1,0,0,0,0
20,21,0,0,0,0,0,0,3,2,8,2,6,1,1,0,0,0
21,22,0,0,0,0,0,0,4,1,17,7,10,7,5,1,0,0
22,23,0,0,0,0,8,2,1,0,3,1,2,2,0,1,0,0
23,24,0,0,0,0,12,3,10,0,7,6,24,11,0,1,0,0
24,25,0,0,0,0,1,1,1,0,0,0,1,1,0,0,0,0
25,26,0,0,0,0,3,0,1,0,0,1,1,2,0,0,0,0
26,27,0,0,0,0,0,0,6,0,0,0,2,0,0,0,0,0
27,28,0,0,0,0,9,4,6,1,1,2,20,15,0,0,0,0
28,29,0,0,0,0,1,0,0,0,0,0,2,1,0,0,0,0
29,30,0,0,0,0,16,2,15,0,97,74,58,74,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,8,3,2,0,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [242]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス      50.0
6月_オス      12.0
7月_メス     192.0
7月_オス      50.0
8月_メス     342.0
8月_オス     300.0
9月_メス     220.0
9月_オス     193.0
10月_メス    258.0
10月_オス    194.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

## CSVとして保存

In [243]:
df.to_csv("セジロウンカ日別誘殺数_2024.csv")

# 2024_トビイロウンカ日別誘殺数

## tabulaによる表の抽出

In [245]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2024.pdf",
    pages = '95',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]


df.drop([0, 1, 8, 9, 10], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 11:57:40 AM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
2,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r3\r0\r0\r0,0\r1\r0\r0\r0,14\r111\r65\r17\r1,10\r40\r75\r14\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,2\r0\r1\r0\r0,2\r0\r1\r0\r0,12\r58\r3\r8\r0,21\r42\r4\r11\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r1\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r3\r6,0\r0\r1\r0\r8,0\r0\r0\r0\r1,0\r0\r0\r0\r0
5,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r3\r7,0\r1\r2\r2\r9,4\r2\r1\r0\r0,6\r0\r0\r1\r1,3\r0\r0\r0\r0,1\r0\r0\r0\r0
6,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r1\r0,5\r9\r2\r2\r0,7\r8\r5\r3\r1,1\r2\r0\r0\r0,0\r1\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
7,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r0\r0,0\r0\r0\r0\r1\r0,0\r0\r0\r0\r3\r0,0\r1\r3\r0\r12,0\r1\r1\r0\r15,0\r1\r0\r0\r0\r0,2\r0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [246]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,0,0,0,0,0,0,0,0,14,10,0,0
1,2,0,0,0,0,0,0,0,0,0,0,3,1,111,40,0,0
2,3,0,0,0,0,0,0,0,0,0,0,0,0,65,75,0,0
3,4,0,0,0,0,0,0,0,0,0,0,0,0,17,14,0,0
4,5,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0
5,6,0,0,0,0,0,0,0,0,0,0,2,2,12,21,0,0
6,7,0,0,0,0,0,0,0,0,0,0,0,0,58,42,0,0
7,8,0,0,0,0,0,0,0,0,0,0,1,1,3,4,0,0
8,9,0,0,0,0,0,0,0,0,0,0,0,0,8,11,0,0
9,10,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
10,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,13,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
13,14,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0
14,15,0,0,0,0,0,0,0,0,0,0,0,0,6,8,1,0
15,16,0,0,0,0,0,0,0,0,0,0,0,0,4,6,3,1
16,17,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0
17,18,0,0,0,0,0,0,0,0,0,0,2,2,1,0,0,0
18,19,0,0,0,0,0,0,0,0,0,0,3,2,0,1,0,0
19,20,0,0,0,0,0,0,0,0,0,0,7,9,0,1,0,0
20,21,0,0,0,0,0,0,0,0,0,0,5,7,1,0,0,0
21,22,0,0,0,0,0,0,0,0,0,0,9,8,2,1,0,0
22,23,0,0,0,0,0,0,0,0,0,0,2,5,0,0,0,0
23,24,0,0,0,0,0,0,0,0,0,1,2,3,0,0,0,0
24,25,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
25,26,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0
26,27,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0
27,28,0,0,0,0,0,0,0,0,0,0,3,1,0,0,0,0
28,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,30,0,0,0,0,0,0,0,0,1,3,12,15,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,0,0,0,0,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [247]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       0.0
5月_オス       0.0
6月_メス       0.0
6月_オス       0.0
7月_メス       0.0
7月_オス       0.0
8月_メス       1.0
8月_オス       4.0
9月_メス      53.0
9月_オス      59.0
10月_メス    309.0
10月_オス    239.0
11月_メス      4.0
11月_オス      1.0
dtype: float64

## CSVとして保存

In [248]:
df.to_csv("トビイロウンカ日別誘殺数_2024.csv")

# 2024_ヒメトビウンカ日別誘殺数

## tabulaによる表の抽出

In [252]:
dfs = tabula.read_pdf(
    "香川県農業試験場病害虫防除所_業務年報_2024.pdf",
    pages = '96',
    lattice=True
    )

# for df in dfs[0:-2]: # list内の1要素が1つの表に対応（dfs[0]と同義）
#     display(df)
# print(type(dfs[0]))
df = dfs[0]


df.drop([0, 1, 8, 9, 10], inplace=True)

df.columns = [
    '日',
    '4月_メス', '4月_オス',
    '5月_メス', '5月_オス',
    '6月_メス', '6月_オス',
    '7月_メス', '7月_オス',
    '8月_メス', '8月_オス',
    '9月_メス', '9月_オス',
    '10月_メス', '10月_オス',
    '11月_メス', '11月_オス'
    ]

df

WARNING:tabula.backend:Got stderr: Sep 16, 2025 12:00:25 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
2,1\r2\r3\r4\r5,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r0\r0\r0\r0,0\r0\r0\r0\r0,2\r3\r2\r141\r19,0\r2\r2\r66\r13,1\r6\r6\r5\r7,1\r9\r11\r2\r13,2\r4\r0\r1\r2,0\r4\r3\r0\r4,0\r1\r3\r3\r0,3\r1\r4\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
3,6\r7\r8\r9\r10,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,14\r21\r15\r23\r10,6\r4\r8\r15\r16,2\r5\r4\r20\r1,8\r4\r7\r9\r3,0\r0\r3\r0\r1,2\r0\r0\r0\r0,15\r2\r0\r2\r0,6\r2\r1\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
4,11\r12\r13\r14\r15,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,1\r0\r0\r2\r1,0\r1\r0\r1\r3,2\r2\r9\r4\r6,3\r1\r20\r11\r2,0\r3\r1\r1\r2,1\r2\r0\r4\r0,0\r0\r1\r1\r2,0\r0\r0\r0\r1,0\r0\r0\r0\r0,0\r0\r0\r0\r0
5,16\r17\r18\r19\r20,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,3\r1\r10\r2\r7,5\r2\r13\r1\r3,2\r2\r5\r4\r7,6\r1\r8\r6\r5,0\r2\r0\r6\r2,0\r0\r3\r3\r3,0\r3\r1\r0\r0,0\r0\r0\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
6,21\r22\r23\r24\r25,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r2\r0\r0,0\r1\r0\r2\r0,15\r13\r5\r21\r0,5\r11\r3\r18\r5,2\r7\r5\r8\r1,2\r6\r4\r4\r1,3\r1\r0\r3\r0,0\r2\r0\r1\r0,0\r2\r2\r0\r0,0\r1\r0\r1\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0
7,26\r27\r28\r29\r30\r31,0\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r1\r0\r0\r0\r0,1\r0\r0\r0\r0\r0,0\r0\r5\r1\r11,0\r0\r0\r1\r9,1\r6\r7\r0\r5\r10,2\r14\r13\r0\r22\r34,0\r0\r0\r0\r9\r0,1\r0\r0\r2\r6\r0,0\r0\r2\r0\r6,1\r0\r1\r1\r3,0\r1\r0\r0\r0\r0,0\r1\r0\r0\r0\r0,0\r0\r0\r0\r0,0\r0\r0\r0\r0

In [253]:
# すべての列を対象に分割
for col in df.columns:
    df[col] = df[col].str.replace(',', '').str.split('\r')

# 各行で「月日」の長さに合わせて他の列をパディング
for col in df.columns:
    max_len = df['日'].map(len) # 各行の「日」の長さ
    new_column = []
    for lst, ml in zip(df[col], max_len):
        if len(lst) < ml:
            new_lst = lst + [np.nan] * (ml - len(lst))
        else:
            new_lst = lst
        new_column.append(new_lst)
    df[col] = new_column

# 各セルがリストになったので，まとめて縦方向にexplode
df = df.explode(list(df.columns), ignore_index=True)

df

,日,4月_メス,4月_オス,5月_メス,5月_オス,6月_メス,6月_オス,7月_メス,7月_オス,8月_メス,8月_オス,9月_メス,9月_オス,10月_メス,10月_オス,11月_メス,11月_オス
0,1,0,0,0,0,1,0,2,0,1,1,2,0,0,3,0,0
1,2,0,0,0,0,0,0,3,2,6,9,4,4,1,1,0,0
2,3,0,0,0,0,0,0,2,2,6,11,0,3,3,4,0,0
3,4,0,0,0,0,0,0,141,66,5,2,1,0,3,1,0,0
4,5,0,0,0,0,0,0,19,13,7,13,2,4,0,0,0,0
5,6,0,0,0,0,0,0,14,6,2,8,0,2,15,6,0,0
6,7,0,0,0,0,0,0,21,4,5,4,0,0,2,2,0,0
7,8,0,0,0,0,0,0,15,8,4,7,3,0,0,1,0,0
8,9,0,0,0,0,0,0,23,15,20,9,0,0,2,1,0,0
9,10,0,0,0,0,0,0,10,16,1,3,1,0,0,0,0,0
10,11,0,0,0,0,0,0,1,0,2,3,0,1,0,0,0,0
11,12,0,0,0,0,0,0,0,1,2,1,3,2,0,0,0,0
12,13,0,0,0,0,0,0,0,0,9,20,1,0,1,0,0,0
13,14,0,0,0,0,0,0,2,1,4,11,1,4,1,0,0,0
14,15,0,0,0,0,0,0,1,3,6,2,2,0,2,1,0,0
15,16,0,0,0,0,0,0,3,5,2,6,0,0,0,0,0,0
16,17,0,0,0,0,0,0,1,2,2,1,2,0,3,0,0,0
17,18,0,0,0,0,0,0,10,13,5,8,0,3,1,0,0,0
18,19,0,0,0,0,0,0,2,1,4,6,6,3,0,1,0,0
19,20,0,0,0,0,0,0,7,3,7,5,2,3,0,0,0,0
20,21,0,0,0,0,0,0,15,5,2,2,3,0,0,0,0,0
21,22,0,0,0,0,0,1,13,11,7,6,1,2,2,1,0,0
22,23,0,0,0,0,2,0,5,3,5,4,0,0,2,0,0,0
23,24,0,0,0,0,0,2,21,18,8,4,3,1,0,1,0,0
24,25,0,0,0,0,0,0,0,5,1,1,0,0,0,0,0,0
25,26,0,0,0,1,0,0,1,2,0,1,0,1,0,0,0,0
26,27,0,0,1,0,0,0,6,14,0,0,0,0,1,1,0,0
27,28,0,0,0,0,5,0,7,13,0,0,2,1,0,0,0,0
28,29,0,0,0,0,1,1,0,0,0,2,0,1,0,0,0,0
29,30,0,0,0,0,11,9,5,22,9,6,6,3,0,0,0,0
30,31,NaN,NaN,0,0,NaN,NaN,10,34,0,0,NaN,NaN,0,0,NaN,NaN

## 誤記チェック

In [254]:
# print(df.dtypes)
# print('---')
df = df.astype('float64') # object -> float64
# print(df.dtypes)

df.sum()

日         496.0
4月_メス       0.0
4月_オス       0.0
5月_メス       1.0
5月_オス       1.0
6月_メス      20.0
6月_オス      13.0
7月_メス     360.0
7月_オス     288.0
8月_メス     132.0
8月_オス     156.0
9月_メス      45.0
9月_オス      38.0
10月_メス     39.0
10月_オス     24.0
11月_メス      0.0
11月_オス      0.0
dtype: float64

## CSVとして保存

In [255]:
df.to_csv("ヒメトビウンカ日別誘殺数_2024.csv")